const moveDB = {

  "Phatom Quill": {"type": "Ghost", "category": "Physical", "power": 90, "accuracy": 100, "pp": 10,priority: 0,crit:0},
  "Blazing Vault": {"type": "Fire", "category": "Physcal", "power": 85, "accuracy": 90, "pp": 10,priority: 1,crit:0 },
  "Aqua Tremor": {"type": "Water", "category": "Physical", "power": 100, "accuracy": 95, "pp": 15, priority: -1,crit:0},

    //1Fire
    "Ember": {"type": "Fire", "category": "Special", "power": 40, "accuracy": 100, "pp": 25,priority: 0,crit:0},
    "Flame Burst": {"type": "Fire", "category": "Special", "power": 70, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Flamethrower": {"type": "Fire", "category": "Special", "power": 90, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Fire Blast": {"type": "Fire", "category": "Special", "power": 110, "accuracy": 85, "pp": 5,priority: 0,crit:0},
    "Overheat": {"type": "Fire", "category": "Special", "power": 130, "accuracy": 90, "pp": 5,priority: 0,crit:0},
    "Fire Fang": {"type": "Fire", "category": "Physical", "power": 65, "accuracy": 95, "pp": 15,priority: 0,crit:0},
    "Fire Punch": {"type": "Fire", "category": "Physical", "power": 75, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Flame Wheel": {"type": "Fire", "category": "Physical", "power": 60, "accuracy": 100, "pp": 25,priority: 0,crit:0},
    "Flare Blitz": {"type": "Fire", "category": "Physical", "power": 120, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Blaze Kick": {"type": "Fire", "category": "Physical", "power": 85, "accuracy": 90, "pp": 10,priority: 0,crit:1},

    //2Water
    "Water Gun": {"type": "Water", "category": "Special", "power": 40, "accuracy": 100, "pp": 25,priority: 0,crit:0},
    "Bubble Beam": {"type": "Water", "category": "Special", "power": 65, "accuracy": 100, "pp": 20,priority: 0,crit:0},
    "Scald": {"type": "Water", "category": "Special", "power": 80, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Surf": {"type": "Water", "category": "Special", "power": 90, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Hydro Pump": {"type": "Water", "category": "Special", "power": 110, "accuracy": 80, "pp": 5,priority: 0,crit:0},
    "Aqua Jet": {"type": "Water", "category": "Physical", "power": 40, "accuracy": 100, "pp": 20,priority: 1,crit:0},
    "Waterfall": {"type": "Water", "category": "Physical", "power": 80, "accuracy": 100, "pp": 15,priority: 0,crit:0},
    "Aqua Tail": {"type": "Water", "category": "Physical", "power": 90, "accuracy": 90, "pp": 10,priority: 0,crit:0},
    "Crabhammer": {"type": "Water", "category": "Physical", "power": 100, "accuracy": 90, "pp": 10,priority: 0,crit:1},
    "Liquidation": {"type": "Water", "category": "Physical", "power": 85, "accuracy": 100, "pp": 10,priority: 0,crit:0},

    //3Grass
  "Absorb":        { type: "Grass", category: "Special", power: 20, accuracy: 100, pp: 25, priority: 0,crit:0 },
  "Mega Drain":    { type: "Grass", category: "Special", power: 40, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Energy Ball":   { type: "Grass", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Solar Beam":    { type: "Grass", category: "Special", power: 120, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Leaf Storm":    { type: "Grass", category: "Special", power: 130, accuracy: 90, pp: 5, priority: 0,crit:0 },
  "Leafage":    { type: "Grass", category: "Physical", power: 40, accuracy: 100, pp: 25, priority: 0,crit:0 },
  "Razor Leaf":    { type: "Grass", category: "Physical", power: 55, accuracy: 95, pp: 25, priority: 0,crit:1 },
  "Seed Bomb":     { type: "Grass", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Leaf Blade":    { type: "Grass", category: "Physical", power: 90, accuracy: 100, pp: 15, priority: 0,crit:1 },
  "Wood Hammer":   { type: "Grass", category: "Physical", power: 120, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Power Whip":    { type: "Grass", category: "Physical", power: 120, accuracy: 85, pp: 10, priority: 0,crit:0 },

  //4Electric
  "Thunder Shock": { type: "Electric", category: "Special", power: 40, accuracy: 100, pp: 30, priority: 0,crit:0 },
  "Electro Ball":  { type: "Electric", category: "Special", power: 60, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Discharge":     { type: "Electric", category: "Special", power: 80, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Thunderbolt":   { type: "Electric", category: "Special", power: 90, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Thunder":       { type: "Electric", category: "Special", power: 110, accuracy: 70, pp: 10, priority: 0,crit:0 },
  "Thunder Fang":  { type: "Electric", category: "Physical", power: 65, accuracy: 95, pp: 15, priority: 0,crit:0 },
  "Spark":         { type: "Electric", category: "Physical", power: 65, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Thunder Punch": { type: "Electric", category: "Physical", power: 75, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Wild Charge":   { type: "Electric", category: "Physical", power: 90, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Volt Tackle":   { type: "Electric", category: "Physical", power: 120, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Zing Zap":      { type: "Electric", category: "Physical", power: 80, accuracy: 100, pp: 10, priority: 0,crit:0 },

  //5Ice
  "Powder Snow":   { type: "Ice", category: "Special", power: 40, accuracy: 100, pp: 25, priority: 0,crit:0 },
  "Icy Wind":      { type: "Ice", category: "Special", power: 55, accuracy: 95, pp: 15, priority: 0,crit:0 },
  "Aurora Beam":      { type: "Ice", category: "Special", power: 65, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Ice Beam":      { type: "Ice", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Blizzard":      { type: "Ice", category: "Special", power: 110, accuracy: 70, pp: 5, priority: 0 ,crit:0},
  "Freeze-Dry":    { type: "Ice", category: "Special", power: 70, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Ice Shard":     { type: "Ice", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1,crit:0 },
  "Ice Fang":      { type: "Ice", category: "Physical", power: 65, accuracy: 95, pp: 15, priority: 0,crit:0 },
  "Icicle Crash":  { type: "Ice", category: "Physical", power: 85, accuracy: 90, pp: 10, priority: 0,crit:0 },
  "Ice Punch":     { type: "Ice", category: "Physical", power: 75, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Avalanche":     { type: "Ice", category: "Physical", power: 60, accuracy: 100, pp: 10, priority: -4,crit:0 },

  //6Ground
  "Mud-Slap":      { type: "Ground", category: "Special", power: 20, accuracy: 85, pp: 10, priority: 0,crit:0 },
  "Mud Shot":      { type: "Ground", category: "Special", power: 55, accuracy: 95, pp: 15, priority: 0,crit:0 },
  "Earth Power":   { type: "Ground", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Bulldoze":      { type: "Ground", category: "Physical", power: 60, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Dig":           { type: "Ground", category: "Physical", power: 80, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Earthquake":    { type: "Ground", category: "Physical", power: 100, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "High Horsepower":{ type: "Ground", category: "Physical", power: 95, accuracy: 95, pp: 10, priority: 0 ,crit:0},

  //7Psychic
  "Confusion":     { type: "Psychic", category: "Special", power: 50, accuracy: 100, pp: 25, priority: 0 ,crit:0},
  "Psybeam":       { type: "Psychic", category: "Special", power: 65, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Psychic":       { type: "Psychic", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Future Sight":  { type: "Psychic", category: "Special", power: 120, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Dream Eater":   { type: "Psychic", category: "Special", power: 100, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Zen Headbutt":  { type: "Psychic", category: "Physical", power: 80, accuracy: 90, pp: 15, priority: 0,crit:0 },
  "Psycho Cut":    { type: "Psychic", category: "Physical", power: 70, accuracy: 100, pp: 20, priority: 0,crit:1 },

  //8Dark
  "Snarl":         { type: "Dark", category: "Special", power: 55, accuracy: 95, pp: 15, priority: 0 ,crit:0},
  "Dark Pulse":    { type: "Dark", category: "Special", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Night Daze":    { type: "Dark", category: "Special", power: 85, accuracy: 95, pp: 10, priority: 0 ,crit:0},
  "Pursuit":       { type: "Dark", category: "Physical", power: 40, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Assurance":     { type: "Dark", category: "Physical", power: 60, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Bite":          { type: "Dark", category: "Physical", power: 60, accuracy: 100, pp: 25, priority: 0 ,crit:0},
  "Crunch":        { type: "Dark", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Knock Off":     { type: "Dark", category: "Physical", power: 65, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Foul Play":     { type: "Dark", category: "Physical", power: 75, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Night Slash":     { type: "Dark", category: "Physical", power: 70, accuracy: 100, pp: 15, priority: 0,crit:1 },
  "Sucker Punch":  { type: "Dark", category: "Physical", power: 70, accuracy: 100, pp: 5, priority: 1 ,crit:0},

  //9Dragon
  "Twister":        { type: "Dragon", category: "Special", power: 40, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Dragon Breath":  { type: "Dragon", category: "Special", power: 60, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Dragon Pulse":   { type: "Dragon", category: "Special", power: 85, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Draco Meteor":   { type: "Dragon", category: "Special", power: 130, accuracy: 90, pp: 5, priority: 0 ,crit:0},
  "Dragon Claw":    { type: "Dragon", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Dragon Tail":    { type: "Dragon", category: "Physical", power: 60, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Outrage":        { type: "Dragon", category: "Physical", power: 120, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Dual Chop":      { type: "Dragon", category: "Physical", power: 40, accuracy: 90, pp: 15, priority: 0 ,crit:0},
  "Breaking Swipe": { type: "Dragon", category: "Physical", power: 60, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Dragon Rush":    { type: "Dragon", category: "Physical", power: 100, accuracy: 75, pp: 15, priority: 0 ,crit:0},

  //10Fairy
  "Fairy Wind":     { type: "Fairy", category: "Special", power: 40, accuracy: 100, pp: 30, priority: 0,crit:0 },
  "Draining Kiss":  { type: "Fairy", category: "Special", power: 50, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Disarming Voice":{ type: "Fairy", category: "Special", power: 40, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Dazzling Gleam": { type: "Fairy", category: "Special", power: 80, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Moonblast":      { type: "Fairy", category: "Special", power: 95, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Play Rough":     { type: "Fairy", category: "Physical", power: 90, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Spirit Break":   { type: "Fairy", category: "Physical", power: 75, accuracy: 100, pp: 10, priority: 0 ,crit:0},

  //11Fighting
  "Vacuum Wave":    { type: "Fighting", category: "Special", power: 40, accuracy: 100, pp: 30, priority: 1 ,crit:0},
  "Aura Sphere":    { type: "Fighting", category: "Special", power: 80, accuracy: true, pp: 20, priority: 0 ,crit:0},
  "Focus Blast":    { type: "Fighting", category: "Special", power: 120, accuracy: 70, pp: 5, priority: 0 ,crit:0},
  "Rock Smash":     { type: "Fighting", category: "Physical", power: 40, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Mach Punch":   { type: "Fighting", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1 ,crit:0},
  "Brick Break":    { type: "Fighting", category: "Physical", power: 75, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Close Combat":   { type: "Fighting", category: "Physical", power: 120, accuracy: 100, pp: 5, priority: 0 ,crit:0},
  "High Jump Kick": { type: "Fighting", category: "Physical", power: 130, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Cross Chop":     { type: "Fighting", category: "Physical", power: 100, accuracy: 80, pp: 5, priority: 0 ,crit:1},

   //12Poison
  "Acid":           { type: "Poison", category: "Special", power: 40, accuracy: 100, pp: 30, priority: 0 ,crit:0},
  "Sludge":         { type: "Poison", category: "Special", power: 65, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Sludge Bomb":    { type: "Poison", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Venoshock":      { type: "Poison", category: "Special", power: 65, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Poison Sting":   { type: "Poison", category: "Physical", power: 15, accuracy: 100, pp: 35, priority: 0,crit:0 },
  "Poison Jab":     { type: "Poison", category: "Physical", power: 80, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Gunk Shot":      { type: "Poison", category: "Physical", power: 120, accuracy: 80, pp: 5, priority: 0,crit:0 },
  "Poison Tail":    { type: "Poison", category: "Physical", power: 50, accuracy: 100, pp: 25, priority: 0 ,crit:1},
  "Cross Poison":   { type: "Poison", category: "Physical", power: 70, accuracy: 100, pp: 20, priority: 0 ,crit:1},

  //13Flying
  "Gust":           { type: "Flying", category: "Special", power: 40, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Air Cutter":     { type: "Flying", category: "Special", power: 60, accuracy: 95, pp: 25, priority: 0,crit:1 },
  "Air Slash":      { type: "Flying", category: "Special", power: 75, accuracy: 95, pp: 15, priority: 0,crit:0 },
  "Hurricane":      { type: "Flying", category: "Special", power: 110, accuracy: 70, pp: 10, priority: 0,crit:0 },
  "Peck":           { type: "Flying", category: "Physical", power: 35, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Pluck":           { type: "Flying", category: "Physical", power: 60, accuracy: 100, pp: 20, priority: 0,crit:0 },
  "Wing Attack":    { type: "Flying", category: "Physical", power: 60, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Aerial Ace":     { type: "Flying", category: "Physical", power: 60, accuracy: true, pp: 20, priority: 0,crit:0 },
  "Brave Bird":     { type: "Flying", category: "Physical", power: 120, accuracy: 100, pp: 15, priority: 0,crit:0 },
  "Drill Peck":     { type: "Flying", category: "Physical", power: 80, accuracy: 100, pp: 20, priority: 0,crit:0 },

  //14Rock
  "Ancient Power":  { type: "Rock", category: "Special", power: 60, accuracy: 100, pp: 5, priority: 0,crit:0 },
  "Power Gem":      { type: "Rock", category: "Special", power: 80, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Accelerock":   { type: "Rcok", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1,crit:0 },
  "Rock Throw":     { type: "Rock", category: "Physical", power: 50, accuracy: 90, pp: 15, priority: 0 ,crit:0},
  "Rock Tomb":      { type: "Rock", category: "Physical", power: 60, accuracy: 95, pp: 15, priority: 0 ,crit:0},
  "Stone Edge":     { type: "Rock", category: "Physical", power: 100, accuracy: 80, pp: 5, priority: 0,crit:1 },
  "Rock Slide":     { type: "Rock", category: "Physical", power: 75, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Smack Down":     { type: "Rock", category: "Physical", power: 50, accuracy: 100, pp: 15, priority: 0,crit:0 },

  //15Ghost
  "Astonish":       { type: "Ghost", category: "Special", power: 30, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Shadow Ball":    { type: "Ghost", category: "Special", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Hex":            { type: "Ghost", category: "Special", power: 65, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Shadow Claw":    { type: "Ghost", category: "Physical", power: 70, accuracy: 100, pp: 15, priority: 0,crit:1},
  "Shadow Sneak":   { type: "Ghost", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1 ,crit:0},
  "Poltergeist":    { type: "Ghost", category: "Physical", power: 110, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Phantom Force":  { type: "Ghost", category: "Physical", power: 90, accuracy: 100, pp: 10, priority: 0 ,crit:0},

  //16Steel
  "Mirror Shot":    { type: "Steel", category: "Special", power: 65, accuracy: 85, pp: 10, priority: 0 ,crit:0},
  "Flash Cannon":   { type: "Steel", category: "Special", power: 80, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Steel Beam":     { type: "Steel", category: "Special", power: 140, accuracy: 95, pp: 5, priority: 0 ,crit:0},
  "Metal Claw":     { type: "Steel", category: "Physical", power: 50, accuracy: 95, pp: 35, priority: 0,crit:0 },
  "Iron Head":      { type: "Steel", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Iron Tail":      { type: "Steel", category: "Physical", power: 100, accuracy: 75, pp: 15, priority: 0 ,crit:0},
  "Meteor Mash":    { type: "Steel", category: "Physical", power: 90, accuracy: 90, pp: 10, priority: 0 ,crit:0},
  "Bullet Punch":   { type: "Steel", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1 ,crit:0},

  //17Bug
  "Struggle Bug":   { type: "Bug", category: "Special", power: 50, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Signal Beam":    { type: "Bug", category: "Special", power: 75, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Bug Buzz":       { type: "Bug", category: "Special", power: 90, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Fury Cutter":    { type: "Bug", category: "Physical", power: 40, accuracy: 95, pp: 20, priority: 0 ,crit:0},
  "X-Scissor":      { type: "Bug", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Megahorn":       { type: "Bug", category: "Physical", power: 120, accuracy: 85, pp: 10, priority: 0 ,crit:0},
  "Leech Life":     { type: "Bug", category: "Physical", power: 80, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "U-turn":         { type: "Bug", category: "Physical", power: 70, accuracy: 100, pp: 20, priority: 0 ,crit:0},

  //18Normal
  "Swift":          { type: "Normal", category: "Special", power: 60, accuracy: true, pp: 20, priority: 0 ,crit:0},
  "Tri Attack":     { type: "Normal", category: "Special", power: 80, accuracy: 100, pp: 10, priority: 0,crit:0 },
  "Hyper Beam":     { type: "Normal", category: "Special", power: 150, accuracy: 90, pp: 5, priority: 0 ,crit:0},
  "Boomburst":      { type: "Normal", category: "Special", power: 140, accuracy: 100, pp: 10, priority: 0 ,crit:0},
  "Scratch":         { type: "Normal", category: "Physical", power: 40, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Tackle":         { type: "Normal", category: "Physical", power: 40, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Splash":         { type: "Normal", category: "Physical", power: 0, accuracy: 100, pp: 35, priority: 0 ,crit:0},
  "Slash":         { type: "Normal", category: "Physical", power: 70, accuracy: 100, pp: 20, priority: 0 ,crit:1},
  "Quick Attack":   { type: "Normal", category: "Physical", power: 40, accuracy: 100, pp: 30, priority: 1 ,crit:0},
  "Headbutt":       { type: "Normal", category: "Physical", power: 70, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Strength":       { type: "Normal", category: "Physical", power: 80, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Double-Edge":    { type: "Normal", category: "Physical", power: 120, accuracy: 100, pp: 15, priority: 0 ,crit:0},
  "Return":         { type: "Normal", category: "Physical", power: 102, accuracy: 100, pp: 20, priority: 0 ,crit:0},
  "Giga Impact":    { type: "Normal", category: "Physical", power: 150, accuracy: 90, pp: 5, priority: 0 ,crit:0}
};
